### ISSUE TITLE
Select on Overview not working 0.9

### ISSUE THREAD

**Issue by swainjo** [gephi/gephi#1306]
If use Select on Overview in Data Laboratory when return to Overview Node is not selected.

**Comment by seinecle** [comment]
+1

**Comment by eduramiba** [comment]
Confirmed, thanks for the report

**Comment by seinecle** [comment]
not sure this is fixed... steps to reproduce:
- open Les Miserables.gexf, pick any node in the data lab and "select in overview"
- not selected in overview

**Comment by eduramiba** [comment]
The fix is not released yet. Are you testing on 0.9.1-SNAPSHOT? If that's the case you will need to wait some time for this build to finish https://travis-ci.org/gephi/gephi/builds/106308753

**Comment by seinecle** [comment]
oh ok. I was assuming it was part of the number of updates just released

**Comment by eduramiba** [comment]
Oh I see, it will be included in next batch of updates.

**Comment by bac3917** [comment]
0.9.1 (downloaded aug 17, 2017) still doesn't have a fix on this... right?

**Comment by eduramiba** [comment]
This should work on 0.9.1 When you use it from data laboratory, make sure you have opened overview first.

**Comment by bhushan-borole** [comment]
> This should work on 0.9.1 When you use it from data laboratory, make sure you have opened overview first.

This is still not working.

**Comment by mirkohu** [comment]
> > This should work on 0.9.1 When you use it from data laboratory, make sure you have opened overview first.
> 
> This is still not working.

Not working for me too. On Gephi 0.9.7

**Comment by pdinduseng** [comment]
Not working for me too

**Comment by J-Mojzis** [comment]
not working for me. It zooms to the selected part but does not highlight.
