### ISSUE TITLE
Importing Adjacency Matrices

### ISSUE THREAD

**Issue by mrichey17** [gephi/gephi#1372]
When importing adjacency matrices (File -> Open), I can only get it to import a CSV if the node names (column 1 and row 1) are numbers (in the case of my dataset, 1 through 935).

If I import with column 1 and row 1 populated with the names of the nodes (simple strings like "Mike" and "Allen"), Gephi does nothing. If I import with the numbers, it will import the matrix.

Is there any way to get it to import using my node names?

**Comment by mbastian** [comment]
Can you share a sample of your file so I can more easily reproduce the error? Thanks!

**Comment by amindehdarian** [comment]
I also have a problem for importing data. In the latest version, when I import data for nodes and links, the process for nodes in fine, but for the links, Gephi imports only part of the data, while in the previous versions it was ok! Has something changed for importing from csv. files?

**Comment by mrichey17** [comment]
So sorry for the delay!

Attached is the matrix I am trying to import (just save as .csv). Again, if I change all the node names to numbers and then semicolon delimit, it works perfectly.

I have also included the attribute file that I want to import in order to associate the node names with the lats/longs. Any ideas?

[TurkeyDistrictNetwork_AdjacencyMatrix.xlsx](https://github.com/gephi/gephi/files/135430/TurkeyDistrictNetwork_AdjacencyMatrix.xlsx)
[TurkeyDistrictNetwork_AttributeFile.xlsx](https://github.com/gephi/gephi/files/135431/TurkeyDistrictNetwork_AttributeFile.xlsx)

**Comment by eduramiba** [comment]
Hi,
We indded have a bug with CSV matrix import where spaces in the ids are causing a wrong number of labesl to be detected.

I consider CSV matrix format kind of horrible because it's very error prone and you have to make sure that:
* Excel does not include empty cells in the export
* You use semicolon and not comma
* Make sure the first line starts with semicolon
* The number of lines and labels is the same

I corrected your files (mostly) and they can be imported correctly:
* I removed spaces from ids
* I converted the label column in attributes file to the id column, otherwise attributes will not be added to nodes with import spreadsheet
* I deleted empty cells in excel (in columns or rows without a label)
* I added zeros to empty cells that actually have a label

Remaining problems => Some ids in attributes file don't match the ids in matrix file for one of these reasons:
* They start uppercase in one place and lowercase in other. Example: Sarkikaraagac vs sarkikaraagac
* They are different due to a typo. Example: Serefilkochisar vs Sereflikochisar

I also attach the resulting gexf file after importing the almost fixed files, so it helps you find the errors in datalab (you will see missing data).

[TurkeyDistrictNetwork.zip](https://github.com/gephi/gephi/files/136984/TurkeyDistrictNetwork.zip)

**Comment by mrichey17** [comment]
Okay, I can import now, I can add the attributes, and I understand the remaining discrepancies. 

Your edits seem to have not preserved the link weights, instead converting everything to zeros? Not a problem; let me see if I can correct the original files, preserving the link weights, but still getting everything to import. 

Thanks so much for the help. Now if only one of the geospatial visualizers was compatible with the new 0.9.1, I could use the lat/longs!

**Comment by eduramiba** [comment]
Import experience and warnings being improved with #1282

**Comment by bellancaf** [comment]
Hi guys :) 

I kinda have the same problem here. I have a csv matrix I can't import. I have tried using both strings and number as ids for the nodes but I get nothing. Like not even an error or anything. 

Any idea? 
[Connection Matrix now.xlsx](https://github.com/gephi/gephi/files/969914/Connection.Matrix.now.xlsx)

**Comment by mrichey17** [comment]
Suspect this is a file cleaning issue....

First off, make sure your file is in csv format. Remove the equations you have concatenating the names and leave only what you need for node names and attributes. Open the file in a text editor and replace all commas with semicolons such that the file is semicolon delimited instead of comma delimited. 

There is also a new plugin called Convert Excel and csv files to networks. That might help.

Clean the data a little and if it still doesn't work, provide updated files and I can try working on it on this end.

**Comment by bellancaf** [comment]
Hi Mrichey17, thank you for your reply, yep the formulas are only on the nodes tab but that is not creating any problems. 

The problem I am having is with the matrix tab and that tab is all nice and clean with no formulas. 
I can't upload CSVs here unfortunately :/

**Comment by mrichey17** [comment]
Make sure the file is semicolon delimited instead of comma delimited. Upload JUST the matrix but delete the column/row headers so it's just the csv just contains the matrix data (and the matrix will be exactly 41x41 in Excel). If that comes in okay, you can then import the names/labels as node attributes after the nodeset has been created from the matrix you import. Does that make sense?

When I did this, the matrix did import on my end, albeit strangely.

**Comment by eduramiba** [comment]
Closing as fixed with #1282

**Comment by bellancaf** [comment]
Eduramiba why would you close that? There are obviously still some problems :/ 
Is it true that I should change it to semic? I did it but nothing changed really. I also tried the matrix only and it wouldnt work.

**Comment by eduramiba** [comment]
Do you mean it's not fixed with latest nightly build as explained at #1282 ? Have in mind this fix is still not available in a final release but should be fixed for future 0.9.2 release.
