### ISSUE TITLE
Gephi 0.9.2 Won't Start - OpenGL JOGL2.3.2/Mesa>=17.2.0 issue with older AMD cards on Linux

### ISSUE THREAD

**Issue by Dan-McG** [gephi/gephi#1898]
## Expected Behavior
Startup success

## Current Behavior
Startup failure.  At the splash screen, Gephi silently quits at the 'Starting Modules' message.

~/.gephi/0.9.2/dev/var/log/messages.log contains:
```
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped
     at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
     at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
```
All system drivers and software on this 2014 laptop is shiny and up to date.

There seem to be several similar unfixed reports of failure to start (I've not linked as they're closed issues)
## Possible Solution
This is a simple although deeply buried problem that seems to have manifested itself due to a kludge between Gephi's JOGL OpenGL dependency (2.3.2 not updated since 2015) and the Mesa renderer after v.17.2.0 released on or about September 2017.  (I've had several Java based OpenGL apps start to sporadically fail on my system - the final straw was Gephi).

The fix is discussed [here](http://forum.jogamp.org/Mesa-17-2-0-renderer-driver-name-change-error-causes-GLProfile-not-mapped-initialization-error-td4038176.html) and [here](https://jogamp.org/bugzilla/show_bug.cgi?id=1357).

To summarise, the fix to JOGL is to patch /src/jogl/classes/jogamp/opengl/GLContextImpl.java:2136 as follows:
```
- final boolean isDriverMesa = glRenderer.contains(MesaSP) || glRenderer.contains("Gallium ");
+ final boolean isDriverMesa = glRenderer.contains(MesaSP) || glRenderer.contains("Gallium ") || glVersion.contains(MesaSP);
```
Applying the fix:
+ clone and build gluegen runtime
+ clone, patch and build jogl
(both described [here](http://jogamp.org/wiki/index.php/Building_JOGL_on_the_command_line).)
+ to the local Maven repo (~/.m2/repository/org/jogamp) install the four built and renamed jars:
gluegen-rt-2.3.2-patched.jar
gluegen-rt-2.3.2-patched natives-linux-amd64
jogl-all-2.3.2-patched.jar
jogl-all-2.3.2-patched-natives-linux-amd64.jar

eg for the last jar:
```
mvn install:install-file /
-Dfile=jogl-all-2.3.2-patched-natives-linux-amd64.jar /
-DgroupId=org.jogamp.jogl /
-DartifactId=jogl-all /
-Dversion-2.3.2-patched /
-Dclassifier=natives-linux-amd64 /
-Dpackaging=jar
```
+ clone gephi, edit gephi/modules/VisualizationImpl/pom.xml appropriately (set <jogl.version> to 2.3.2-patched and comment out unbuilt jogl and gluegen runtime dependencies eg windows)
+ build and succeed

## Context

This isn't a Gephi problem, it's a dependency problem, but is just recorded here for info.  How can a JOGL bump from the 2015 v2.3.2 be encouraged or how to get Maven Central to incorporate their patch?

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Tried OpenJDK8 and Oracle JDK8
* Operating System: Archlinux (kernel 4.14.13)

Graphics Card: AMD Radeon 7500G [Northern Islands family, ARUBA(Trinity)] OpenGL4.x compatible
Driver: radeon (free version of proprietary ATI driver provided by package xf86-video-ati v.1:7.10.0)
OpenGL core version string: 4.1
OpenGL version string: 3.0
Mesa renderer: 17.3.2
JOGL version: 2.3.2 (patched as above)

**Comment by eduramiba** [comment]
Hi,
Thanks for the detailed bug report and suggested fix.

Currently, I am implementing a new OpenGL rendering engine for Gephi from scratch.
I will take this into account when testing it. I have tested it with recent Mesa drivers, but with an Intel graphics card.

I wish new versions of JOGL will keep coming, some bugs are already fixed in their repositories, but no new release since 2015.

**Comment by aleferna** [comment]
Have the same problem but with brand new Nvidia 1060 system running Ubuntu 17.10. I manage to get the preview to work by manually updating the bluegen and jogl jars with the latest version, but preview is still not working...

**Comment by mbastian** [comment]
Hi, since 0.9.3 we include the latest patched version of JOGL so this is hopefully resolved. If not, please reopen.
